services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sudheer@123
      MYSQL_DATABASE: StudentRecords
      MYSQL_USER: sudheer
      MYSQL_PASSWORD: sudheer@8201
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pSudheer@123"]
      interval: 5s
      retries: 10
      start_period: 10s

  app:
    build: .
    container_name: springboot-app1
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/StudentRecords
      SPRING_DATASOURCE_USERNAME: sudheer
      SPRING_DATASOURCE_PASSWORD: sudheer@8201
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      APP_JWT_SECRET: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
      APP_JWT_EXPIRATION_MS: 604800000
      APP_PORT: 9090
    ports:
      - "8080:9090"
    networks:
      - spring-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mysql_data:

networks:
  spring-network:
